// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS_s06XTu8_ev1rcYBfbk7IHBMe4VHh1s',
    appId: '1:422265029495:web:bb1afdfe3c67e6aa015772',
    messagingSenderId: '422265029495',
    projectId: 'basedispos',
    authDomain: 'basedispos.firebaseapp.com',
    storageBucket: 'basedispos.firebasestorage.app',
    measurementId: 'G-0ESNSSWVJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcX8uehZvZB5pUFzSkyCnPehgcDa4mb6w',
    appId: '1:422265029495:android:8ca5be3a44428c73015772',
    messagingSenderId: '422265029495',
    projectId: 'basedispos',
    storageBucket: 'basedispos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfFkVe-EcuAl0QUDkIbamUIp40JzuhO64',
    appId: '1:422265029495:ios:6b0ef8b570469a39015772',
    messagingSenderId: '422265029495',
    projectId: 'basedispos',
    storageBucket: 'basedispos.firebasestorage.app',
    iosBundleId: 'com.example.workshoucbexplorer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfFkVe-EcuAl0QUDkIbamUIp40JzuhO64',
    appId: '1:422265029495:ios:6b0ef8b570469a39015772',
    messagingSenderId: '422265029495',
    projectId: 'basedispos',
    storageBucket: 'basedispos.firebasestorage.app',
    iosBundleId: 'com.example.workshoucbexplorer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS_s06XTu8_ev1rcYBfbk7IHBMe4VHh1s',
    appId: '1:422265029495:web:9e21258a4981b8e0015772',
    messagingSenderId: '422265029495',
    projectId: 'basedispos',
    authDomain: 'basedispos.firebaseapp.com',
    storageBucket: 'basedispos.firebasestorage.app',
    measurementId: 'G-9P0VP5V3RT',
  );
}